### PR TITLE
Fixed Issue #22 create a post

### LINKED ISSUE #22: Create screen for writing post
Create a screen for writing a new post. The screen should have text boxes for post title, post content, a file picker for adding image, and obviously the submit button.

The component should take a prop `onSubmit` whose value will be a function. This prop function should be called with the user-entered post title, content and image as arguments when the user clicks on the submit button. You can add any other props that you require (stream name, for example).

### PR DESCRIPTION
**Pull request by SD-320808**
Resolves #22 create a post
Screenshot (51)
Screenshot (52)
Screenshot (53)
Screenshot (54)
Screenshot (55)
Screenshot (56)
Screenshot (57)

### CODE REVIEW

File: src/screens/createPost/index.js [hunk 1]
```diff
@@ -0,0 +1,202 @@
...
+                  else setText1(false);
+                  if (document.getElementById("post-content").value === "")
+                    setText2(true);
+                  else setText2(false);
+                  if (
+                    !(
+                      document.getElementById("post-title").value === "" ||
+                      document.getElementById("post-content").value === ""
+                    )
+                  ) {
```
Comment (NilayMajorwar) [inline src/screens/createPost/index.js:183]: Instead of using the `document` API, you can use a React ref - see [`React.useRef`](https://reactjs.org/docs/hooks-reference.html#useref). Essentially, refs are for maintaining a direct reference to DOM elements.

File: src/screens/createPost/index.js [hunk 2]
```diff
@@ -0,0 +1,202 @@
...
+        maxFileSize={5000000}
+        onClose={handleClose}
+      />
+    </div>
+  );
+}
+
+export default function Maxmised(props) {
+  const classes = useStyles();
+  var imgarr = [];
```
Comment (NilayMajorwar) [inline src/screens/createPost/index.js:115]: It's safer to use a React ref for this.

File: src/screens/createPost/index.js [hunk 3]
```diff
@@ -0,0 +1,204 @@
...
+                  ) {
+                    setText1(false);
+                    setText2(false);
+                    props.onSubmit(
+                      inputEl1.current.value,
+                      inputEl2.current.value,
+                      imgarr
+                    );
+                  }
+                }}
```
Comment (NilayMajorwar) [inline src/screens/createPost/index.js:194]: Extract this into a function (inside this component itself), and use that function here. The general code pattern is to keep component logic in the functions and UI in the return value.
